project_id = "fbcviuapotdfenycjgtz"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.check-email-status]
    verify_jwt = false
  [functions.create-cpf-test-users]
    verify_jwt = false
  [functions.deactivate-account]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
